### PR TITLE
Add "Troubling Trends in Machine Learning Scholarship"

### PR DESCRIPTION
**Pull request by sherjilozair**

### CODE REVIEW

**Comment by chobeat** [comment]
I've read only the introduction so far. This paper seems to be addressed to Machine Learning researchers only. While the trends listed there are probably a symptom (or a cause?) of many of the phenomena covered in the reading list, I feel like this paper might be too specific and too narrow to really fit in the reading list.

Nonetheless you raise a good point in creating a section dedicated to the Academia: I feel there should be material on the existing criticism to the current state of the Academia in the west and there's nothing.

**Comment by sherjilozair** [comment]
Yes, I agree that it's addressed at ML researchers. However, as you say I do think many of these reasons are both symptoms and causes of the way ML is being used in industry. Yarden Katz's paper also refers to ML academia a number of times, and this paper could be useful to provide a window to what's happening in ML academia. You could add a note explaining the paper's intended audience, and that it's in the list to provide a perspective from inside machine learning academia. Up to you.

Another article that has a more general audience is this one by Michael Jordan: https://medium.com/@mijordan3/artificial-intelligence-the-revolution-hasnt-happened-yet-5e1d5812e1e7

**Comment by sherjilozair** [comment]
@chobeat I recommend reading section 3.2 and 3.4 which imo are highly relevant for the topic of this reading list.

**Comment by chobeat** [comment]
For now I've added the second article you linked. The critique it's a bit weak since he stays technical but I think it's good introductory material.

**Pull request closed without merging**
