### PR TITLE
Add Tiqqun's The Cybernetic Hypothesis

### PR DESCRIPTION
**Pull request by fabianhjr**

### CODE REVIEW

**Comment by chobeat** [comment]
I'll try to read it today or tomorrow and accept the PR.

**Comment by fabianhjr** [comment]
Hey, I am just pinging you @chobeat.

**Comment by chobeat** [comment]
Yes, I began reading it but it's quite dense. A consideration I have is that it probably fits more in the "Meta" category (because so far it's quite general) than in the AI. I can't promise you I will resume reading it before the Christmas Holiday but I have in plan to finish it.

**Comment by fabianhjr** [comment]
Happy holiday, no worries and no hurries. :3

**Comment by chobeat** [comment]
Hello,

I finally had time to read it. While a good read that elaborates on a topic that is very recurrent, I believe this particular  piece doesn't really fit in the reading list. While the content is of interest for our target, the form is probably unapproachable for most of them and prior readings (Deleuze and Guattari at least) are necessary to really understand what is being said.

So I would argue that this piece doesn't fit the reading list because your average software engineer would just drop it after a few lines, while the piece totally belongs to any advanced reading list on these same subjects.

**Pull request closed without merging**
